### ISSUE TITLE
I was saddened by life, then i found this

### ISSUE THREAD

**Issue by sagewhocodes** [aca123321/cp_books#1]
I was disappointed saddened upset let down disheartened downhearted cast down downcast depressed dispirited discouraged despondent dismayed crestfallen distressed chagrined disenchanted disillusioned displeased discontented dissatisfied upset let down disheartened downhearted cast down downcast depressed dispirited discouraged despondent dismayed crestfallen distressed chagrined disenchanted disillusioned displeased discontented dissatisfied frustrated disgruntled choked miffed cut up gutted as sick as a parrot by life but  then i found this repo.
Thank you acasam for this repo

**Comment by ajargrey** [comment]
Can confirm!
